inherit_from:
  - .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/*.local.rb'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

# there are useful expectations of methods being called on the subject in tests
RSpec/SubjectStub:
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/lib/web_of_science/harvester_spec.rb" # cop doesn't get compound matchers have semantic grouping

# https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/PercentStringArray:
  Exclude:
    - "spec/lib/web_of_science/query_author_spec.rb" # specifically testing quoted clauses w/in strings

Metrics/LineLength:
  Exclude:
    - "spec/factories/**/*" # factories contain long string literals

Naming/VariableName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails/Blank:
  UnlessPresent: false

Style/NumericPredicate:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
