inherit_from:
  - .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/*.local.rb'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Rails/DynamicFindBy:
  Enabled: false

# there are useful expectations of methods being called on the subject in tests
RSpec/SubjectStub:
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/lib/web_of_science/harvester_spec.rb" # cop doesn't get compound matchers have semantic grouping

# https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/PercentStringArray:
  Exclude:
    - "spec/lib/web_of_science/query_author_spec.rb" # specifically testing quoted clauses w/in strings

Layout/LineLength:
  Max: 160 # Intentionally liberal because many existing long lines.
  Exclude:
    - "spec/factories/**/*" # factories contain long string literals
    - "spec/lib/csl/citation_spec.rb"
    - "spec/models/publication_spec.rb"
    - "spec/lib/pubmed/query_author_spec.rb"
    - "spec/lib/bibtex_ingester_spec.rb"

Metrics/AbcSize:
  Max: 35
  Exclude:
    - "spec/controllers/publications_controller_spec.rb"
    - "script/*"

Metrics/BlockLength:
  Exclude:
    - "spec/factories/user_submitted_source_records.rb"
    - "spec/lib/csl/citation_spec.rb"
    - "lib/smci_report.rb"
    - "lib/tasks/*.rake"
    - "script/*"
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - "script/*"

Metrics/ClassLength:
  Max: 120
  Exclude:
    - "app/controllers/authorships_controller.rb"
    - "app/controllers/publications_controller.rb"
    - "app/models/author.rb"
    - "app/models/publication.rb"
    - "app/models/pubmed_source_record.rb"
    - "app/models/sciencewire_source_record.rb"
    - "lib/bibtex_ingester.rb"
    - "lib/cap/authors_poller.rb"
    - "lib/science_wire_publication.rb"
    - "lib/smci_report.rb"
    - "lib/web_of_science/identifiers.rb"
    - "script/*"

Metrics/MethodLength:
  Max: 45
  Exclude:
    - "app/models/pubmed_source_record.rb"
    - "app/models/sciencewire_source_record.rb"
    - "lib/bibtex_ingester.rb"
    - "lib/csl/mapper.rb"
    - "lib/smci_report.rb"
    - "script/*"
    - "spec/**/*"

Metrics/PerceivedComplexity:
  Max: 13
  Exclude:
    - "script/*"

Naming/VariableName:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - "spec/**/*"
    - "script/**/*"

RSpec/NestedGroups:
  Max: 5

# When enabled, produces errors.
RSpec/FactoryBot:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# New cops
Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true

Rails/ActiveRecordCallbacksOrder: # (new in 2.7)
  Enabled: true
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: true
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/FindById: # (new in 2.7)
  Enabled: true
Rails/Inquiry: # (new in 2.7)
  Enabled: true
Rails/MailerName: # (new in 2.7)
  Enabled: true
Rails/MatchRoute: # (new in 2.7)
  Enabled: true
Rails/NegateInclude: # (new in 2.7)
  Enabled: true
Rails/Pluck: # (new in 2.7)
  Enabled: true
Rails/PluckInWhere: # (new in 2.7)
  Enabled: true
Rails/RenderInline: # (new in 2.7)
  Enabled: true
Rails/RenderPlainText: # (new in 2.7)
  Enabled: true
Rails/ShortI18n: # (new in 2.7)
  Enabled: true
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: true
Rails/WhereExists: # (new in 2.7)
  Enabled: true
Rails/WhereNot: # (new in 2.8)
  Enabled: true
