inherit_gem:
  dlss_cops: "config/dlss_baseline.yml"

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - 'lib/tasks/*.rake'
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/*.local.rb'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

# https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/VariableName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
