inherit_gem:
  dlss_cops: "config/dlss_baseline.yml"

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - 'lib/tasks/*.rake'
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/*.local.rb'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/lib/web_of_science/harvester_spec.rb" # cop doesn't get compound matchers have semantic grouping

# https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/PercentStringArray:
  Exclude:
    - "spec/lib/web_of_science/query_author_spec.rb" # specifically testing quoted clauses w/in strings

Metrics/LineLength:
  Exclude:
    - "spec/factories/**/*" # factories contain long string literals

Style/VariableName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
