inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
  RunRailsCops: true

# Offense count: 66
Metrics/AbcSize:
  Max: 288

# Offense count: 2
Metrics/BlockNesting:
  Max: 4

# Offense count: 10
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 464

# Offense count: 17
Metrics/CyclomaticComplexity:
  Max: 52

# Offense count: 896
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 792

# Offense count: 87
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 98

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8

# Offense count: 19
Metrics/PerceivedComplexity:
  Max: 53

# Offense count: 65
Style/Documentation:
  Enabled: false
