sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.4
  - 2.4.1
services: mysql
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rake db:create db:setup
script: bundle exec rake ci
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - CC_TEST_REPORTER_ID=66a4c4244af78b2eaf74c47fed9bfa88560c30c2c9a4e921053f6cd7ce097677
notifications:
  email: false
  slack:
    rooms:
      secure: IrTNB/M3sRhaDjoUhMeBU0rjb/SOnMK4fYcUJJWc+wyrTcccvg/HYdvn2IJJqdgLPb3ffIAGYi12NriN686aLYHH21ph/dQueBpKoVIL2JuRZZ0ltenQjwkCFXh+R95s9MfIccpP3KlqostlNhz/JvRkOcUxyr+treutJhfGPBAAp1uy12pnIDL36TiYhIW2sSOfK4JeNB7A1p8/ik9woV7GTqM06roBSNQY4gHP3Fy81drqnsf2fT4/fFvuj1trz46Ms9oWjH+nT04JOLEJG/Ef9R/r2YIxUX86joNY6whFAirkO4CioHiNJ5L1nsR92ksGBAvCjy2EvOBZbX11cQTeAZ15VERFZttPy2ZProLfyTxVQYwte6FkxVwesIq75Tk1MyIDgdp3uLhbwyh+iwBPLSROsSrdPWmLr7xxuzHi5P+IEOJk+BOsoRcmxa6957Gf2cjLkIDSz4VpigBkpLL8pVqQgPt9hFhg6VuXcofSm231mjW4KRhi4+rEj8mikp1PpdzNoAogj0C2rX9BwErgAko1XHvGxe3vrH3Xu7JfXAE/lVAGIQKIh9gvHoaKOLzX9178/8k8unjo9F6MpbMk7ErVWPTSRmwp9uXQnqQZVTYGbFzU5XeET6dWtBMePODo3ih0ktM5JR/M/8YI4eLASwidY8UdsFDnQfzGW3c=
