services:
  mariadb:
   image: mariadb:10.3 # the version installed on prod
   ports:
     - 3306:3306
   environment:
     MARIADB_DATABASE: sul-pub # same DB name as prod
     MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
