services:
  postgres:
    image: postgres:16 # use the same version as deployed environments
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
