version: '3.6'

services:
  mysqldb:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: sulbib_development
     MYSQL_USER: sulbib
     MYSQL_PASSWORD: sulbib
   volumes:
     - mysql:/var/lib/mysql
     - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
