version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.6.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
      - ruby-rails/test-rails:
          name: test
          context: dlss
          api-only: true # do not try to muck with JavaScript
