# config/application.yml
defaults: &defaults

  sw_doc_type_mappings:
    conference:
      - Clinical Conference
      - Congresses
      - Consensus Development Conference
      - Consensus Development Conference NIH
      - Meeting Abstract
      - Meeting Summary
      - Meeting-Abstract
      - Overall
      - Proceedings Paper
    book:
      - Dictionary
      - Directory
      - Government Publications

  sul_doc_types:
    inproceedings: inproceedings
    book: book
    article: article

  cap_provenance: cap

  cap_population_name: CAP

  manual_source: manual

  sciencewire_source: sciencewire

  pubmed_source: pubmed

  batch_source: batch

  sciencewire_harvest_max: 2

  sw_doc_types_to_skip_a:
    - Book Review
    - Comment
    - Film Review
    - Hardware Review
    - Legal Cases
    - Letter
    - Meeting Abstract
    - Meeting Summary
    - Meeting-Abstract
    - Music Performance Review
    - Music Score
    - Music Score Review
    - News
    - Note
    - Patient Education Handout
    - Poetry
    - Record Review
    - Software Review
    - TV Review Radio Review Video
    - Technical Report
    - Theater Review


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
