---
:get_token_uri: ***REMOVED***
:get_token_port: 443
:get_token_path: /oauth/token
***REMOVED***
:get_token_pass: ***REMOVED***
:authorship_api_uri: irt-dev.stanford.edu
:authorship_api_path: /cap-api/api/cap/v1/authors
:authorship_api_port: 443
:access_token: eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjEzNzExMzMzNzgsInNjb3BlIjpbInByb2ZpbGVzLnJlYWRfYWxsIl0sImF1ZCI6WyJwcm9maWxlcyJdLCJpc3MiOiJodHRwczovL2F1dGh6LXRlc3Quc3RhbmZvcmQuZWR1IiwianRpIjoiNDUzOWU1MTMtNTgxZC00MDA3LWI4MWUtZDRmNzVhNzE5OWQxIiwiY2xpZW50X2lkIjoic3VsIn0.G-gxkdQ5Uwdo8oE4Vc0GTSO_rKAO8gPLPNdNcDIupePhxbpyh40dhdSyzH4xmMBAYhwQG5yGs0hZXjLPIWJ1LrpnmOdlzh24PD6c5Gq3P0gVOO58sY110hrJfwfjdLYmOK5FgXzohghi_GYzWkjdG_3maxQ4OMGfGBQlkSb3TZ_53EDK4bPvcBj2N-XI98CS48SHTAJgbtxAb6bvHgk-thYgZj5w554-bCuwPyRr8MftimutYVi1FBiKSV1Ra8dfSpMDkfZSiokCG0UkNdYJaHlb9fjQuKrvF5u3iVNY95fPOEuWdo8KNCt57FsFrxGY0ualDTSlInHjpgCmpPf6kA
:authorship_api_uri_qa: irt-dev.stanford.edu
:authorship_api_path_qa: /cap-api-qa/api/cap/v1/authors
