---
:get_token_uri: ***REMOVED***
:get_token_port: 443
:get_token_path: /oauth/token
***REMOVED***
:get_token_pass: ***REMOVED***
:authorship_api_uri: irt-dev.stanford.edu
:authorship_api_path: /cap-api/api/cap/v1/authors
:authorship_api_port: 443
:access_token: eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjEzNzA0ODUwMjgsInNjb3BlIjpbInByb2ZpbGVzLnJlYWRfYWxsIl0sImF1ZCI6WyJwcm9maWxlcyJdLCJpc3MiOiJodHRwczovL2F1dGh6LXRlc3Quc3RhbmZvcmQuZWR1IiwianRpIjoiMTc5ZjAzYjMtNzkzOC00YzFjLWI4OTgtZmZhYTkxNGQyNjIwIiwiY2xpZW50X2lkIjoic3VsIn0.AtAD5HS2Y6kasNcpnJKLz3Czc-E-9fjBOSumkebP-yonBjsowcIG3LmYipw-4HIlEz07mIveZ9TGmO9lSm8HX-VEH3Omy6loVCOdNOn8t86qtN9F_ZZI3Ia_03ajhkc6jaLclPQoZ62E7Wgkqd7LHVmrgZ4KImWCt0oO11aTeUh_5KEyslex4H9GGSPp9jaBsy3V7kXX16j4Anaw43J0Zqyb10D9nUwmNA6cdnOwQW-hyf8T3K-WegqMl5Ej_16sSSVCC80t6Cr3k_iMyV90lGk57x_VrjQGx52-vfv2ykghQbxtqyL5EwYySp53rKRChIo2XqhuheoN5QtAaoNE_A
:authorship_api_uri_qa: irt-dev.stanford.edu
:authorship_api_path_qa: /cap-api-qa/api/cap/v1/authors