---
:get_token_uri: ***REMOVED***
:get_token_port: 443
:get_token_path: /oauth/token
***REMOVED***
:get_token_pass: ***REMOVED***
:authorship_api_uri: irt-dev.stanford.edu
:authorship_api_path: /cap-api/api/cap/v1/authors
:authorship_api_port: 443
:access_token: eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjEzNzA2MDkyNTUsInNjb3BlIjpbInByb2ZpbGVzLnJlYWRfYWxsIl0sImF1ZCI6WyJwcm9maWxlcyJdLCJpc3MiOiJodHRwczovL2F1dGh6LXRlc3Quc3RhbmZvcmQuZWR1IiwianRpIjoiYTllMmViNDktYTYyZi00NTFiLWFiNWEtZTJiYzA0ZmRkOGI2IiwiY2xpZW50X2lkIjoic3VsIn0.Ui_u-XTHZDx57bsUjcnLo6K0RkiQ5fRve5WV6aojGb_os1-4C7xjUVDW09NDBk7qfkR1CwmXgeJP3zxeq5GPbpu80UiyDJMUb49_y-itYpeg6CWd58iPhG5WZq21X7G49FWld2ys_nGZ-bLIAHvVjVySZyR6uYkxdbuUlvE5C8hqS8NYYtN57PiwECASvW1v0jvvb0Oy8QnJ7c2tygXarsvf_zgJP5CGNd4sla__VsY6du__pDu_vOE081IqZAs5SAGtTWsWt846u6muFhLpBgbQr-_FQq-y130NjvAVaQXBaWpg3MN3Px246tYZ2nM7yNFOAQVQ67tyE_x33hMeXw
:authorship_api_uri_qa: irt-dev.stanford.edu
:authorship_api_path_qa: /cap-api-qa/api/cap/v1/authors
