---
:get_token_uri: ***REMOVED***
:get_token_port: 443
:get_token_path: /oauth/token
***REMOVED***
:get_token_pass: ***REMOVED***
:authorship_api_uri: irt-dev.stanford.edu
:authorship_api_path: /cap-api/api/cap/v1/authors
:authorship_api_port: 443
:access_token: eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjEzNzE3MzM0ODMsInNjb3BlIjpbInByb2ZpbGVzLnJlYWRfYWxsIl0sImF1ZCI6WyJwcm9maWxlcyJdLCJpc3MiOiJodHRwczovL2F1dGh6LXRlc3Quc3RhbmZvcmQuZWR1IiwianRpIjoiZWQ5NmNjNjMtOTUyMy00YjYwLTgxODgtOGU1N2E0OGM1N2VkIiwiY2xpZW50X2lkIjoic3VsIn0.Ti23KvDOUqszOi1b62OEz5mn7-a8uQQTF2oP26ChzpGk4CXmDWspVNUPzwZW2wtakUDeHMbHuyiSkHAdNxfXvU5IFnAsxHB870byF-eQIecZEzuna_sEx4ywolru2I8nMMFboI12siXoiHxbRLs1fminaLhwd5eXjqQKeI-uvtZl8wQfrAfdCnFzH9WkV4k4kVnFbX_avPKttcexbwTrIVdVmtV1uSkbrcu7EW4mP8tHanoxKBa93YZpjwWjiNg2FuHJault-fTFIi_VzZs2_7dQsVsKocKVyGxKozFoVmsrFSHIvEifihE-9V5ZGCnVnwA-F2CKuaAHwgaQGFCaBA
:authorship_api_uri_qa: irt-dev.stanford.edu
:authorship_api_path_qa: /cap-api-qa/api/cap/v1/authors
