API_KEY: a fake key

## Settings for URI identifier prefixes used in the data; they should be working values in production
SULPUB_ID:
  PUB_URI: http://sulcap.stanford.edu/publications
  AUTHOR_URI: http://sulcap.stanford.edu/authors
  AUTHORSHIP_URI: http://sulcap.stanford.edu/authorship
  SEARCHWORKS_URI: http://searchworks.stanford.edu/?search_field=advanced&number=

## Cap Auth Config
CAP:
  LOG: log/cap.log
  PROFILE_ID_REWRITE_LOG: log/cap_profile_id_rewrite.log
  TOKEN_PATH: /oauth/token
  TOKEN_URI: https://authz.stanford.edu
  TOKEN_USER: sul
  TOKEN_PASS: something
  AUTHORSHIP_API_PATH: /cap-api/api/cap/v1/authors
  AUTHORSHIP_API_PORT: 443
  AUTHORSHIP_API_URI: https://cap-uat.stanford.edu
  HARVEST_ON_CHANGE: true

MAIS:
  LOG: log/mais.log
  BASE_URL: https://aswstest.stanford.edu
  CLIENT_ID: 5d127563-6cbf-4275-98eb-FAKE
  CLIENT_SECRET: 19ad9c72-80dd-46d9-b7eb-FAKE

## PubMed Auth Config
PUBMED:
  LOG: log/pubmed.log
  lookup_enabled: true # this only enables/disables manual pubmed lookups via the publication search and record augmentation; harvests are set below
  harvest_enabled: true # this only enables/disables regular harvests, it will still allow manual entries via pubmed and record augmentation if set above
  FETCH_PATH: /entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml
  SEARCH_PATH: /entrez/eutils/esearch.fcgi?db=pubmed&retmode=xml
  API_KEY: a_fake_pubmed_key
  BASE_URI: https://eutils.ncbi.nlm.nih.gov
  ARTICLE_BASE_URI: https://www.ncbi.nlm.nih.gov/pubmed/
  max_publications_per_author: 3000 # if more than this number of publications are returned for a single author, the author harvest will be aborted
                                    #  and a HB alert will be sent
  # In number of days
  regular_harvest_timeframe: 21
  update_timeframe: null # default pubmed reldate for updated authors resulting from nightly cap polling
  new_author_timeframe: null # default pubmed reldate for new authors resulting from nightly cap polling (null == for all time)

## Sciencewire Auth Config
SCIENCEWIRE:
  LOG: log/sciencewire.log
  BASE_URI: https://sciencewirerest.discoverylogic.com
  HOST: stg.sciencewirerest.discoverylogic.com
  RECOMMENDATION_PATH: /PublicationCatalog/MatchedPublicationItemIdsForAuthor?format=xml
  TMPDIR: /tmp
  ARTICLE_BASE_URI: https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/

## Web Of Science Auth Config
WOS:
  enabled: true # this enables/disables the entire client (harvesting and record fetching)
  ACCEPTED_DBS:
    - WOS
    - MEDLINE
  AUTH_CODE: secret
  LOG: log/web_of_science.log
  LOG_LEVEL: warn
  regular_harvest_timeframe: 3week # default WoS symbolicTimeSpan for regular harvests
  update_timeframe: null # default WoS symbolicTimeSpan for updated authors resulting from nightly cap polling
  new_author_timeframe: null # default WoS symbolicTimeSpan for new authors resulting from nightly cap polling (null == for all time)
  # note, see lib/web_of_science/queries.rb#construct_uid_query
  #   or https://github.com/sul-dlss/sul_pub/wiki/Clarivate-APIs for allowed values of symbolicTimeSpan
  max_publications_per_author: 3000 # if more than this number of publications are returned for a single author, the author harvest will be aborted
                                    #  and a HB alert will be sent

ORCID:
  BASE_URL: https://api.sandbox.orcid.org
  BASE_AUTH_URL: https://sandbox.orcid.org
  BASE_PUBLIC_URL: https://pub.sandbox.orcid.org
  CLIENT_ID: APP-FAKEJMB7RBQVFQ0D
  CLIENT_SECRET: FAKE6bb5-dba1-445d-ba10-c14745383ba0
  LOG: log/orcid.log
  orcidid_for_check: https://sandbox.orcid.org/0000-0002-7262-6251 # jtim

DOI:
  BASE_URI: https://doi.org/

HARVESTER:
  LOG: log/all_sources_harvester.log
  USE_MIDDLE_NAME: true
  USE_FIRST_INITIAL: false
  USE_AUTHOR_IDENTITIES: false
  INSTITUTION:
    name: Stanford University
    address:
      line1: ''
      line2: ''
      city: Stanford
      state: CA
      country: USA

## Ported from application.yml
sw_doc_type_mappings:
  conference:
    - Clinical Conference
    - Congresses
    - Consensus Development Conference
    - Consensus Development Conference NIH
    - Meeting Abstract
    - Meeting Summary
    - Meeting-Abstract
    - Overall
    - Proceedings Paper
  book:
    - Dictionary
    - Directory
    - Government Publications

sul_doc_types:
  inproceedings: inproceedings
  book: book
  article: article

batch_source: batch
cap_provenance: cap
pubmed_source: pubmed
sciencewire_source: sciencewire
wos_source: wos

# checkin keys for honeybadger (actual keys are in shared_configs per environment as needed)
# see https://app.honeybadger.io/projects/50046/check_ins
honeybadger_checkins:
  harvest_all_authors: null
  cap_poll: null
  mais_update_authors: null
  orcid_all_all_works: null
