API_KEY: a fake key

## Settings for URI identifier prefixes used in the data; they should be working values in production
SULPUB_ID:
  PUB_URI: http://sulcap.stanford.edu/publications
  AUTHOR_URI: http://sulcap.stanford.edu/authors
  AUTHORSHIP_URI: http://sulcap.stanford.edu/authorship
  SEARCHWORKS_URI: http://searchworks.stanford.edu/?search_field=advanced&number=

BIBTEX:
  IMPORT:
    DIR: data/bibtex_import_files
    LOG: log/bibtext_import.log

## Cap Auth Config
CAP:
  LOG: log/cap.log
  PROFILE_ID_REWRITE_LOG: log/cap_profile_id_rewrite.log
  PORT: 443
  TOKEN_PATH: /oauth/token
  TOKEN_URI: https://authz.stanford.edu
  TOKEN_USER: sul
  TOKEN_PASS: something
  AUTHORSHIP_API_PATH: /cap-api/api/cap/v1/authors
  AUTHORSHIP_API_PORT: 443
  AUTHORSHIP_API_URI: https://cap-uat.stanford.edu

## PubMed Auth Config
PUBMED:
  LOG: log/pubmed.log
  FETCH_PATH: /entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml
  BASE_URI: https://eutils.ncbi.nlm.nih.gov
  ARTICLE_BASE_URI: https://www.ncbi.nlm.nih.gov/pubmed/

## Sciencewire Auth Config
SCIENCEWIRE:
  enabled: true
  LOG: log/sciencewire.log
  BASE_URI: https://sciencewirerest.discoverylogic.com
  HOST: stg.sciencewirerest.discoverylogic.com
  LICENSE_ID: some-license-id
  RECOMMENDATION_PATH: /PublicationCatalog/MatchedPublicationItemIdsForAuthor?format=xml
  TMPDIR: /tmp
  ARTICLE_BASE_URI: https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/

## Web Of Science Auth Config
WOS:
  enabled: true
  ACCEPTED_DBS:
    - WOS
    - MEDLINE
  AUTH_CODE: secret
  LOG: log/web_of_science.log
  LOG_LEVEL: warn

DOI:
  BASE_URI: https://dx.doi.org/

HARVESTER:
  USE_MIDDLE_NAME: true
  USE_FIRST_INITIAL: false
  USE_AUTHOR_IDENTITIES: false
  INSTITUTION:
    name: Stanford University
    address:
      line1: ''
      line2: ''
      city: Stanford
      state: CA
      country: USA

## Ported from application.yml
sw_doc_type_mappings:
  conference:
    - Clinical Conference
    - Congresses
    - Consensus Development Conference
    - Consensus Development Conference NIH
    - Meeting Abstract
    - Meeting Summary
    - Meeting-Abstract
    - Overall
    - Proceedings Paper
  book:
    - Dictionary
    - Directory
    - Government Publications

sul_doc_types:
  inproceedings: inproceedings
  book: book
  article: article

batch_source: batch
cap_provenance: cap
manual_source: manual
pubmed_source: pubmed
sciencewire_source: sciencewire
wos_source: wos

sw_doc_types_to_skip:
  - Book Review
  - Comment
  - Film Review
  - Hardware Review
  - Legal Cases
  - Letter
  - Meeting Abstract
  - Meeting Summary
  - Meeting-Abstract
  - Music Performance Review
  - Music Score
  - Music Score Review
  - News
  - Note
  - Patient Education Handout
  - Poetry
  - Record Review
  - Software Review
  - TV Review Radio Review Video
  - Technical Report
  - Theater Review
