API_KEY: ***REMOVED***

## Cap Auth Config
CAP:
  TOKEN_URI: something
  PORT: 443
  TOKEN_PATH: /oauth/token
  TOKEN_USER: something
  TOKEN_PASS: something
  AUTHORSHIP_API_URI: something
  AUTHORSHIP_API_PATH: /cap-api-qa/api/cap/v1/authors
  AUTHORSHIP_API_PORT: 443

## Sciencewire Auth Config
SCIENCEWIRE:
  BASE_URI: sciencewirerest.discoverylogic.com
  PORT: 443
  RECOMMENDATION_PATH: /PublicationCatalog/MatchedPublicationItemIdsForAuthor?format=xml
  LICENSE_ID: some-license-id
  HOST: sciencewirerest.discoverylogic.com
  PUBLICATION_ITEMS_PATH: /PublicationCatalog/PublicationItems?format=xml&publicationItemIDs=
  PUBLICATION_QUERY_PATH: /PublicationCatalog/PublicationQuery?format=xml
