module PublicationQueryXsd
  ##
  # An initial guess at an XSD for the author PublicationQuery.
  # This was generated by http://www.freeformatter.com/xsd-generator.html
  # The output was visually inspected and it seems to be reasonable; it was
  # created from various example data in the SW-API documentation. Note that this
  # particular version of the XSD is more specific to the AuthorPublicationQuery
  # used in sul-pub, it might not capture all the possible Filter options.
  def publication_query_xsd
    xsd = <<-XSD
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="query">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Criterion">
          <xs:complexType>
            <xs:all>

              <xs:element name="Criteria" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="Criterion" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:all>

                          <xs:element name="TextSearch" minOccurs="0">
                            <xs:complexType>
                              <xs:all>
                                <xs:element type="xs:string" name="QueryPredicate"/>
                                <xs:element type="xs:string" name="SearchType"/>
                                <xs:element type="xs:string" name="Columns"/>
                                <xs:element type="xs:integer" name="MaximumRows"/>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>

                          <xs:element name="Filter" minOccurs="0">
                            <xs:complexType>
                              <xs:all>
                                <xs:element type="xs:string" name="Column"/>
                                <xs:element type="xs:string" name="Operator"/>
                                <xs:element type="xs:string" name="Value" minOccurs="0"/>
                                <xs:element name="Values" minOccurs="0">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="Value" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>

                        </xs:all>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:all>
            <xs:attribute type="xs:string" name="ConjunctionOperator"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="Columns" minOccurs="0">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="SortColumn" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element type="xs:string" name="Column"/>
                    <xs:element type="xs:string" name="Direction"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element type="xs:integer" name="MaximumRows" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>
XSD
    Nokogiri::XML::Schema(xsd)
  end
end
